import Head from "next/head";
import dynamic from "next/dynamic";
import Awards from "../components/awards/Awards";
import AboutUs from "../components/aboutUs/AboutUs";
const Services = dynamic(() => import("../components/services/Services"));
const Contacts = dynamic(() => import("../components/contacts/Contacts"));
const Works = dynamic(() => import("../components/works/Works"));
import Divider from "../components/divider/divider";

export default function Home() {
  return (
    <>
      <Head>
        <title>Inteo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600&family=Playfair+Display:ital,wght@0,400;0,500;1,400;1,500&display=swap"
          media="bogus"
        />
        {/* <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <style data-href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600&family=Playfair+Display:ital,wght@0,400;0,500;1,400;1,500&display=swap">
          @import
          url(https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600&family=Playfair+Display:ital,wght@0,400;0,500;1,400;1,500&display=swap);
        </style> */}
      </Head>
      <main>
        <Awards />
        <AboutUs />
        <Divider />
        <Services />
        <Works />
        <Divider />
        <Contacts />
        <Divider />
      </main>
      <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600&family=Playfair+Display:ital,wght@0,400;0,500;1,400;1,500&display=swap"
      />
    </>
  );
}
